services:
  elasticsearch:
    build:
      context: containers/Elasticsearch/
      dockerfile: Dockerfile
    container_name: esn01
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./containers/Elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - app-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      retries: 5

  kibana:
    build:
      context: containers/Kibana/
      dockerfile: Dockerfile
    container_name: kib01
    volumes:
      - ./containers/Kibana/exported:/usr/share/kibana/exported
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app-network
    depends_on:
      - elasticsearch
  
  devcontainer:
    build:
      context: .devcontainer/
      dockerfile: Dockerfile
    container_name: dev-container
    volumes:
      - .:/workspace:cached
    networks:
      - app-network
    command: sleep infinity
    depends_on:
      - elasticsearch
    profiles:
      - dev  # Only start with --profile dev

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    networks:
      app-network:
        ipv4_address: 172.28.0.10
    depends_on:
      - postgres

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      ZBX_SERVER_HOST: zabbix-server
    networks:
      - app-network
    depends_on:
      - zabbix-server

  postgres:
    image: postgres:15-alpine
    container_name: postgres00
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  pipeline-state:  # Shared volume for state management
  zabbix-db-data:
  zabbix-server-data: